server:
  port: 8079
spring:
  application:
    name: fraud-service

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    password: Anya12102000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true